### ISSUE TITLE
Suggestion - provide cli option for keeping mps open after media ends

### ISSUE THREAD

**Issue by edrozenberg** [donmelton/MPlayerShell#15]
In some cases it's nice to be able to keep the movie window open after it finishes playing, such as
"oops fell asleep for that ending and now want to back up" :)

The suggestions I found online for doing this with mplayer don't work because mps doesn't support idle.

http://superuser.com.80bola.com/questions/355576/keep-mplayer-open-after-video-playback

    $ mplayer test.ogg -idle -fixed-vo

http://wiki.multimedia.cx.80bola.com/index.php?title=MPlayer_FAQ#General_Questions
http://www1.mplayerhq.hu.80bola.com/DOCS/tech/slave.txt

    $ mplayer -slave -idle -input=/fifo

**Comment by donmelton** [comment]
@edrozenberg MPlayerShell can't support MPlayer's `-idle` option because, as it says in my `man` page, "MPlayerShell is the process controlling MPlayer."

And your justification for the feature seems like an usually odd example. :) I'm not inclined to add this. Note that MPV doesn't have a feature like this either.

**Comment by edrozenberg** [comment]
GUI players usually keep the video player open but since this is a cli app it makes sense for it to quit sometime :). Thanks.
